version: '3.8'

networks:
  backend:
    driver: bridge
    name: ${APP_NAME}-backend

services:
  app:
    container_name: ${APP_NAME}-app
    build:
      context: docker/php
      dockerfile: docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
        APP_NAME: ${APP_NAME}
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
  nginx:
    image: nginx:${NGINX_VERSION}-alpine
    container_name: ${APP_NAME}-nginx
    depends_on:
      - app
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd
    restart: unless-stopped
    networks:
      - backend
